/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatprogramdemo;

/**
 *
 * @author death
 */
import java.net.Socket;
import javax.swing.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Client extends javax.swing.JFrame implements Runnable {

    Socket managerSocket = null; //Socket of the manager program
    String managerIP = "";      // Manager IP
    int managerPort = 0;        // Manager port
    String staffName = "";      // name of the staff
    DataOutputStream out = null; // Output buffer
    ChatPanel panel = null;
    Thread t;

    /**
     * Creates new form Staff
     */
    public Client() {
        initComponents();
        this.btnConnect.setEnabled(true);
        this.add("North", this.jPanel1);
        this.add("Center", this.jPanel2);
        this.setSize(700, 500);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblStaff = new javax.swing.JLabel();
        txtStaff = new javax.swing.JTextField();
        lblServerIP = new javax.swing.JLabel();
        txtServerIP = new javax.swing.JTextField();
        lblPort = new javax.swing.JLabel();
        txtServerPort = new javax.swing.JTextField();
        btnConnect = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Staff and Sever Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 0, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(521, 44));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(533, 60));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        lblStaff.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStaff.setText("Staff: ");
        jPanel1.add(lblStaff);
        jPanel1.add(txtStaff);

        lblServerIP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServerIP.setText("Server IP: ");
        jPanel1.add(lblServerIP);
        jPanel1.add(txtServerIP);

        lblPort.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPort.setText("Port: ");
        jPanel1.add(lblPort);
        jPanel1.add(txtServerPort);

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        jPanel1.add(btnConnect);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 984, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
        this.btnConnect.setEnabled(false);
        managerIP = this.txtServerIP.getText();
        managerPort = Integer.parseInt(this.txtServerPort.getText());
        staffName = this.txtStaff.getText();
        try {
            managerSocket = new Socket(managerIP, managerPort);
            if (managerSocket != null)//Connect successed
            {
                //Create chat compoment and add it to the GUI
                panel = new ChatPanel(managerSocket, staffName, "Manager");
                panel.getTxtSentText().append("Manager is running\n");
                this.getContentPane().add(panel);
                t = new Thread(this);
                t.start();
                panel.updateUI();
                //Get the socket output stream
                out = new DataOutputStream(managerSocket.getOutputStream());
                //Announce to manager
                out.writeBytes(staffName);
                out.write(13);
                out.write(10);
                out.flush();
            }
        } catch (Exception e) {
            this.btnConnect.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Manager is not running");
//            System.exit(0);
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    public void terminate() {
        jPanel2 = null;
        this.txtServerIP.setText("");
        this.txtServerPort.setText("");
        this.txtStaff.setText("");
        this.btnConnect.setEnabled(true);
        panel.setDisable();

    }

    @Override
    public void run() {
        while (true) {
            try {
                if (panel.getTerminated()) {
                    terminate();
                    panel.setTerminate(false);
                }
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblServerIP;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JTextField txtServerIP;
    private javax.swing.JTextField txtServerPort;
    private javax.swing.JTextField txtStaff;
    // End of variables declaration//GEN-END:variables
}
